# Generated by Django 5.2.9 on 2026-03-12 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cualificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_esco', models.URLField(unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_eqf', models.IntegerField(blank=True, help_text='Nivel Marco Europeo (1-8)', null=True)),
            ],
            options={
                'verbose_name': 'Cualificación',
                'verbose_name_plural': 'Cualificaciones',
            },
        ),
        migrations.CreateModel(
            name='GrupoHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jerarquico', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('uri_esco', models.URLField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de Habilidad',
                'verbose_name_plural': 'Grupos de Habilidades',
            },
        ),
        migrations.CreateModel(
            name='GrupoISCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_isco', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('uri_esco', models.URLField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo ISCO',
                'verbose_name_plural': 'Grupos ISCO',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dir3', models.CharField(max_length=9, unique=True, verbose_name='Código DIR3')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='talento.empleado')),
                ('qualifications', models.ManyToManyField(blank=True, to='talento.cualificacion', verbose_name='Titulaciones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.empleado')),
                ('evaluador_personal', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormacionRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('horas', models.IntegerField()),
                ('organismo', models.CharField(max_length=100)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='talento.evaluaciondesempeño')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_esco', models.URLField(unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('skill/competence', 'Habilidad/Competencia'), ('knowledge', 'Conocimiento')], max_length=50)),
                ('nivel_reuso', models.CharField(blank=True, choices=[('transversal', 'Transversal'), ('sector-specific', 'Específica del sector'), ('occupation-specific', 'Específica de la ocupación'), ('cross-sector', 'Intersectorial')], max_length=50)),
                ('etiquetas_alternativas', models.TextField(blank=True, help_text='Sinónimos (altLabels)')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_transversal_oficial', models.BooleanField(default=False)),
                ('grupo_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talento.grupohabilidad')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subhabilidades', to='talento.habilidadue')),
            ],
            options={
                'verbose_name': 'Habilidad/Conocimiento',
                'verbose_name_plural': 'Habilidades/Conocimientos',
            },
        ),
        migrations.CreateModel(
            name='LogroObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='talento.evaluaciondesempeño')),
            ],
        ),
        migrations.CreateModel(
            name='MeritoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PUB', 'Publicación'), ('DOC', 'Docencia/Tutoría')], max_length=3)),
                ('descripcion', models.CharField(max_length=255)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meritos', to='talento.evaluaciondesempeño')),
            ],
        ),
        migrations.CreateModel(
            name='NivelHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_empleado', models.CharField(choices=[('1', 'Básico'), ('2', 'Intermedio'), ('3', 'Avanzado'), ('4', 'Experto')], max_length=1)),
                ('explicacion_empleado', models.TextField(blank=True)),
                ('nivel_jefe', models.CharField(blank=True, choices=[('1', 'Básico'), ('2', 'Intermedio'), ('3', 'Avanzado'), ('4', 'Experto')], max_length=1, null=True)),
                ('explicacion_jefe', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sus_habilidades', to='talento.empleado')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.habilidadue')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_esco', models.URLField(unique=True)),
                ('codigo_esco', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('etiquetas_alternativas', models.TextField(blank=True)),
                ('definicion', models.TextField(blank=True, null=True)),
                ('grupo_isco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='talento.grupoisco')),
                ('habilidades_esenciales', models.ManyToManyField(blank=True, related_name='esencial_en', to='talento.habilidadue')),
                ('habilidades_opcionales', models.ManyToManyField(blank=True, related_name='opcional_en', to='talento.habilidadue')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subpuestos', to='talento.ocupacion')),
            ],
            options={
                'verbose_name': 'Ocupación (Puesto)',
                'verbose_name_plural': 'Ocupaciones (Puestos)',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nivel', models.IntegerField(default=18)),
                ('grupo', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('habilidades_minimas', models.ManyToManyField(blank=True, to='talento.habilidadue', verbose_name='Requisitos RPT')),
                ('ocupaciones_esco', models.ManyToManyField(blank=True, to='talento.ocupacion', verbose_name='Equivalencias ESCO')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talento.unidadorganica')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talento.puesto'),
        ),
    ]
