# Generated by Django 5.2.9 on 2026-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cualificacion',
            name='tipo',
            field=models.CharField(choices=[('ESCO', 'ESCO'), ('RUCT', 'Universitaria (RUCT)'), ('FP', 'Formación Profesional'), ('INCUAL', 'Cualificación Profesional INCUAL'), ('INTERNA', 'Formación Interna')], default='ESCO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cualificacion',
            name='nivel_eqf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cualificacion',
            name='uri_esco',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
