# Generated by Django 5.2.9 on 2026-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0002_cualificacion_tipo_alter_cualificacion_nivel_eqf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cualificacion',
            name='codigo_oficial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
