# Generated by Django 5.2.9 on 2026-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0003_cualificacion_codigo_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cualificacion',
            name='universidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
