# Generated by Django 5.2.9 on 2026-03-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0004_cualificacion_universidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaIncual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('nivel', models.IntegerField()),
                ('familia', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('nivel', models.IntegerField()),
                ('familia', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cualificacion_incual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='talento.competenciaincual')),
            ],
        ),
        migrations.CreateModel(
            name='CualificacionUnidadCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cualificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.cualificacion')),
                ('unidad_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.unidadcompetencia')),
            ],
            options={
                'unique_together': {('cualificacion', 'unidad_competencia')},
            },
        ),
    ]
