# Generated by Django 5.2.9 on 2026-03-22 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0005_competenciaincual_unidadcompetencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de alta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja_jubilacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja/jubilación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones internas'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto_actual',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='empleados_activos', to='talento.puesto', verbose_name='Puesto Actual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='DNI/NIE'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_actuales', to='talento.empleado', verbose_name='Jefe/a Directo actual'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='HistoricoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('fecha_inicio', models.DateField(verbose_name='Desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('motivo_cambio', models.CharField(blank=True, max_length=255, verbose_name='Motivo del cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puestos', to='talento.empleado')),
                ('jefe_en_ese_momento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_subordinados', to='talento.empleado', verbose_name='Jefe/a durante este periodo')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talento.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Histórico de Puesto',
                'verbose_name_plural': 'Historial de Puestos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TitulacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('fecha_obtencion', models.DateField(blank=True, null=True, verbose_name='Fecha de obtención')),
                ('centro_expedidor', models.CharField(blank=True, max_length=250, verbose_name='Centro/Universidad')),
                ('horas_totales', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de horas')),
                ('cualificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talento.cualificacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_titulaciones', to='talento.empleado')),
            ],
            options={
                'verbose_name': 'Titulación del Empleado',
                'verbose_name_plural': 'Titulaciones de Empleados',
                'unique_together': {('empleado', 'cualificacion', 'fecha_obtencion')},
            },
        ),
    ]
