# Generated by Django 5.2.9 on 2026-03-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0006_alter_empleado_options_remove_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('origen', models.CharField(choices=[('RPT', 'Requisito del Puesto'), ('EXTRA', 'A mayores (Seleccionada del listado)')], default='EXTRA', max_length=10, verbose_name='Origen de la competencia')),
                ('nivel_requerido', models.CharField(choices=[('1', '1 - Básico'), ('2', '2 - Intermedio'), ('3', '3 - Avanzado'), ('4', '4 - Experto')], default='1', help_text='Nivel mínimo exigido por la RPT', max_length=1)),
                ('nivel_jefe', models.CharField(blank=True, choices=[('1', '1 - Básico'), ('2', '2 - Intermedio'), ('3', '3 - Avanzado'), ('4', '4 - Experto')], max_length=1, null=True, verbose_name='Nivel evaluado por Jefe')),
                ('observaciones_jefe', models.TextField(blank=True, verbose_name='Comentarios del Evaluador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mochila', to='talento.empleado')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.habilidadue', verbose_name='Habilidad (ESCO)')),
            ],
            options={
                'verbose_name': 'Competencia del Empleado',
                'verbose_name_plural': 'Mochila de Competencias',
                'unique_together': {('empleado', 'habilidad')},
            },
        ),
        migrations.DeleteModel(
            name='NivelHabilidad',
        ),
    ]
