# Generated by Django 5.2.9 on 2026-03-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0007_competenciaempleado_delete_nivelhabilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadorganica',
            options={'ordering': ['codigo_ayto'], 'verbose_name': 'Unidad Orgánica', 'verbose_name_plural': 'Organigrama (Unidades)'},
        ),
        migrations.AddField(
            model_name='unidadorganica',
            name='codigo_ayto',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Código Interno Ayto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadorganica',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subunidades', to='talento.unidadorganica', verbose_name='Unidad Superior'),
        ),
        migrations.AlterField(
            model_name='unidadorganica',
            name='codigo_dir3',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Código DIR3'),
        ),
    ]
