# Generated by Django 5.2.9 on 2026-03-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0008_alter_unidadorganica_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='unidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='unidad_organica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talento.unidadorganica', verbose_name='Unidad/Departamento Actual'),
        ),
        migrations.AddField(
            model_name='historicopuesto',
            name='unidad_organica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talento.unidadorganica'),
        ),
    ]
