# Generated by Django 5.2.9 on 2026-03-24 19:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0009_remove_puesto_unidad_empleado_unidad_organica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Definición según Anexo II')),
                ('bloque', models.CharField(choices=[('TAREA', 'Desempeño de la Tarea (Bloque A)'), ('CONTEXTUAL', 'Desempeño Contextual (Bloque B)')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='logroobjetivo',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='meritoextra',
            name='evaluacion',
        ),
        migrations.AlterModelOptions(
            name='evaluaciondesempeño',
            options={'verbose_name': 'Evaluación de Desempeño', 'verbose_name_plural': 'Evaluaciones de Desempeño'},
        ),
        migrations.RemoveField(
            model_name='evaluaciondesempeño',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='evaluaciondesempeño',
            name='evaluador_personal',
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='año',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='evaluador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_firmadas', to='talento.empleado'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='fecha_evaluacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='puntos_formacion_innovacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='puntos_objetivos_colectivos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='puntos_objetivos_individuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluaciondesempeño',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='talento.empleado'),
        ),
        migrations.CreateModel(
            name='NotaDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(help_text='1: Muy insuficiente, 2: Insuficiente, 3: Bueno, 4: Excelente', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.dimensionevaluacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_notas', to='talento.evaluaciondesempeño')),
            ],
            options={
                'unique_together': {('evaluacion', 'dimension')},
            },
        ),
        migrations.DeleteModel(
            name='FormacionRealizada',
        ),
        migrations.DeleteModel(
            name='LogroObjetivo',
        ),
        migrations.DeleteModel(
            name='MeritoExtra',
        ),
    ]
