# Generated by Django 5.2.9 on 2026-03-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0010_dimensionevaluacion_remove_logroobjetivo_evaluacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadcompetencia',
            name='cualificacion_incual',
        ),
        migrations.AlterUniqueTogether(
            name='cualificacionunidadcompetencia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cualificacionunidadcompetencia',
            name='cualificacion',
        ),
        migrations.RemoveField(
            model_name='cualificacionunidadcompetencia',
            name='unidad_competencia',
        ),
        migrations.DeleteModel(
            name='CompetenciaIncual',
        ),
        migrations.DeleteModel(
            name='CualificacionUnidadCompetencia',
        ),
        migrations.DeleteModel(
            name='UnidadCompetencia',
        ),
    ]
