# Generated by Django 5.2.9 on 2026-03-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0011_remove_unidadcompetencia_cualificacion_incual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'verbose_name': 'Puesto de Trabajo (RPT)', 'verbose_name_plural': 'Puestos de Trabajo (RPT)'},
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='habilidades_minimas',
        ),
        migrations.AddField(
            model_name='puesto',
            name='habilidades_rpt',
            field=models.ManyToManyField(blank=True, related_name='puestos_rpt', to='talento.habilidadue', verbose_name='Habilidades RPT (Específicas Ayto)'),
        ),
        migrations.AlterField(
            model_name='competenciaempleado',
            name='habilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talento.habilidadue', verbose_name='Habilidad/Competencia'),
        ),
        migrations.AlterField(
            model_name='competenciaempleado',
            name='nivel_jefe',
            field=models.CharField(choices=[('0', '0 - Sin evaluar / No requerido'), ('1', '1 - Básico'), ('2', '2 - Intermedio'), ('3', '3 - Avanzado'), ('4', '4 - Experto')], default='0', max_length=1, verbose_name='Evaluación Jefe'),
        ),
        migrations.AlterField(
            model_name='competenciaempleado',
            name='nivel_requerido',
            field=models.CharField(choices=[('0', '0 - Sin evaluar / No requerido'), ('1', '1 - Básico'), ('2', '2 - Intermedio'), ('3', '3 - Avanzado'), ('4', '4 - Experto')], default='0', max_length=1, verbose_name='Nivel Requerido'),
        ),
        migrations.AlterField(
            model_name='competenciaempleado',
            name='observaciones_jefe',
            field=models.TextField(blank=True, help_text='Notas sobre el desempeño o evidencias de la competencia', verbose_name='Comentarios del Evaluador'),
        ),
        migrations.AlterField(
            model_name='competenciaempleado',
            name='origen',
            field=models.CharField(choices=[('RPT', 'Requisito RPT (Ayto)'), ('ESCO_OBL', 'Obligatoria (ESCO)'), ('ESCO_OPC', 'Opcional (ESCO)'), ('EXTRA', 'A mayores / Otras')], default='RPT', max_length=10, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='grupo',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Grupo de Clasificación'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivel',
            field=models.IntegerField(default=18, verbose_name='Nivel de Complemento de Destino'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Puesto'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='ocupaciones_esco',
            field=models.ManyToManyField(blank=True, related_name='puestos_equivalentes', to='talento.ocupacion', verbose_name='Equivalencias Ocupación ESCO'),
        ),
    ]
