# Generated by Django 5.2.9 on 2026-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0012_alter_puesto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenciaempleado',
            name='nivel_requerido',
        ),
        migrations.AddField(
            model_name='competenciaempleado',
            name='nivel_autoevaluacion',
            field=models.CharField(choices=[('0', '0 - Sin evaluar / No requerido'), ('1', '1 - Básico'), ('2', '2 - Intermedio'), ('3', '3 - Avanzado'), ('4', '4 - Experto')], default='0', max_length=1, verbose_name='Autoevaluación'),
        ),
    ]
