# Generated by Django 5.2.9 on 2026-03-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0013_remove_competenciaempleado_nivel_requerido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciondesempeño',
            name='puntos_formacion_innovacion',
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='informe_final',
            field=models.TextField(blank=True, verbose_name='Informe Justificativo'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='puntos_formacion_III',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Área III'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='puntos_innovacion_IV',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Área IV'),
        ),
        migrations.CreateModel(
            name='MeritoCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(choices=[('AREA_III', 'Área III: Formación y Transferencia'), ('AREA_IV', 'Área IV: Innovación e Investigación')], max_length=20, verbose_name='Tipo de Área')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título del Curso o Proyecto')),
                ('entidad', models.CharField(max_length=250, verbose_name='Organismo/Centro')),
                ('fecha', models.DateField(verbose_name='Fecha de finalización')),
                ('horas', models.PositiveIntegerField(default=0, verbose_name='Número de horas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_meritos', to='talento.empleado')),
            ],
            options={
                'verbose_name': 'Mérito de Carrera',
                'verbose_name_plural': 'Méritos de Carrera',
                'ordering': ['-fecha'],
            },
        ),
    ]
