# Generated by Django 5.2.9 on 2026-04-03 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0014_remove_evaluaciondesempeño_puntos_formacion_innovacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupohabilidad',
            options={'verbose_name': 'Grupo de Habilidades', 'verbose_name_plural': 'Grupos de Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='historicopuesto',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Histórico del Puesto', 'verbose_name_plural': 'Historial de Puestos'},
        ),
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'verbose_name': 'Ocupación', 'verbose_name_plural': 'Ocupaciones'},
        ),
        migrations.AddField(
            model_name='competenciaempleado',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='competenciaempleado',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='cualificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cualificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='cualificacion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cualificacion',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='grupohabilidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupohabilidad',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='grupohabilidad',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='grupohabilidad',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='grupoisco',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupoisco',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='grupoisco',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='grupoisco',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='habilidadue',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habilidadue',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='habilidadue',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='habilidadue',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicopuesto',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='historicopuesto',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='meritocarrera',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meritocarrera',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='meritocarrera',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='meritocarrera',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='notadimension',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notadimension',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='notadimension',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='notadimension',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puesto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='titulacionempleado',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='titulacionempleado',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='unidadorganica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadorganica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='unidadorganica',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creador', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='unidadorganica',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='dimensionevaluacion',
            name='bloque',
            field=models.CharField(choices=[('TAREA', 'Desempeño de la Tarea'), ('CONTEXTUAL', 'Desempeño Contextual')], max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluaciondesempeño',
            name='puntos_formacion_III',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Puntos Formación'),
        ),
        migrations.AlterField(
            model_name='evaluaciondesempeño',
            name='puntos_innovacion_IV',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Puntos Innovación'),
        ),
        migrations.AlterField(
            model_name='meritocarrera',
            name='bloque',
            field=models.CharField(choices=[('AREA_III', 'Formación y Transferencia'), ('AREA_IV', 'Innovación e Investigación')], max_length=20, verbose_name='Tipo de Área'),
        ),
    ]
