# Generated by Django 5.2.9 on 2026-04-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0015_alter_grupohabilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notadimension',
            options={'verbose_name': 'Dimensión de Evaluación', 'verbose_name_plural': 'Dimensiones de Evaluación'},
        ),
    ]
