# Generated by Django 5.2.9 on 2026-04-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0016_alter_notadimension_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensionevaluacion',
            options={'verbose_name': 'Dimensión de Evaluación', 'verbose_name_plural': 'Dimensiones de Evaluación'},
        ),
    ]
