# Generated by Django 5.2.9 on 2026-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0017_alter_dimensionevaluacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaempleado',
            name='observaciones_empleado',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios del Empleado'),
        ),
    ]
