# Generated by Django 5.2.9 on 2026-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0018_competenciaempleado_observaciones_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notadimension',
            options={'verbose_name': 'Nota de Dimensión', 'verbose_name_plural': 'Notas de Dimensiones'},
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='es_obligatoria',
            field=models.BooleanField(default=True, verbose_name='¿Es obligatoria para el informe?'),
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='subgrupo_aplicable',
            field=models.CharField(choices=[('A', 'Subgrupos A1/A2'), ('C', 'Subgrupos C1/C2'), ('TODOS', 'Común a todos')], default='TODOS', max_length=10, verbose_name='Subgrupo al que aplica'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='descripcion_objetivos_colectivos',
            field=models.TextField(blank=True, null=True, verbose_name='Memoria de Objetivos Colectivos'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='descripcion_objetivos_individuales',
            field=models.TextField(blank=True, null=True, verbose_name='Memoria de Objetivos Individuales'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (En proceso)'), ('CERRADA', 'Cerrada / Definitiva')], default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluaciondesempeño',
            name='informe_final',
            field=models.TextField(blank=True, verbose_name='Informe Cualitativo Final'),
        ),
    ]
